import Head from 'next/head'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <h1>Home</h1>
      <p>여러가지 기능을 만들어보는 테스트 프로젝트입니다</p>
      <ul>
        <li>다크모드</li>
        <li>JSON_SERVER + TodoList</li>
      </ul>
    </>
  )
}
